### PR TITLE
Please update the snap

### PR DESCRIPTION
**Pull request by RCMainak**
Please update the snap version on snap store.

### CODE REVIEW

**Comment by RCMainak** [comment]
@ChrisMacNaughton Can you please update the snap to the latest released version? Thanks.

**Comment by ChrisMacNaughton** [comment]
Somewhat annoyingly, this repo isn't actually the source for the Alacritty snap at this point - it's broadly an old fork that was used to introduce the snapcraft config. At this point, the snap creation is basically a bit of repo munging from master on the main version to build the new version.

**Comment by RCMainak** [comment]
I see! Sorry for ruining your weekend. If you can tell me who is maintaining the snap now, maybe I can follow up with them. :confused: 

Thanks for creating the snap in the fast place. :smile:

**Comment by ChrisMacNaughton** [comment]
No worries, it didn't ruin my weekend! The edge channel of the snap has been updated to 0.5.0-dev!

**Comment by RCMainak** [comment]
Thanks :smile: 

Btw, you can close this PR since I opened it because the issues on this repo is disabled. Also if you want to guide me maybe I can help you update the snap instead of asking you to update every time there is a new release :sweat_smile:

**Comment by ChrisMacNaughton** [comment]
Unfortunately, I don't know that there's a good way to share the update bits, as upstream Alacritty decided to move the snap config stuff around a while back. The updating is a manual process that's mostly handled by another guy at Canonical. The snap may move ownership at some point to a group to maintain it. The best place to discuss it would probably be on https://forum.snapcraft.io/

**Pull request closed without merging**
